Employee_details_webapp/Employee_details_webapp/Models/AddViewModel.cs
using DomainLayer.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Employee_details_webapp.Models
{
	public class AddViewModel
	{
        [Key]
        public int Employeeid { get; set; }
        
        public int Personid { get; set; }
        
        public int Positionid { get; set; }

        public int Salary { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int EmployeeCode { get; set; }
        public Boolean ISDisabled { get; set; } = false;


        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }


    }
}

Employee_details_webapp/Employee_details_webapp/Models/CombinedViewModel.cs
using DomainLayer.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Employee_details_webapp.Models
{
	public class CombinedViewModel
	{
        public string? FirstName { get; set; }
        public string? MiddleName { get; set; }
        public string? LastName { get; set; }
        public string? Address { get; set; }
        public string? Email { get; set; }

        public Guid Employeeid { get; set; }
        public int Salary { get; set; } = 0;
        public DateOnly StartDate { get; set; }
        public DateOnly EndDate { get; set; }
        public int EmployeeCode { get; set; } = 0;
        public Boolean ISDisabled { get; set; } = false;
        public Guid Personid { get; set; }
        public Guid Positionid { get; set; }

        public string? PositionName { get; set; }

    }
}

Employee_details_webapp/Employee_details_webapp/Models/ErrorViewModel.cs
namespace Employee_details_webapp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Employee_details_webapp/Employee_details_webapp/Models/PositionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Employee_details_webapp.Models
{
	public class PositionViewModel
	{
        public Guid Positionid { get; set; }
        public string? PositionName { get; set; }

    }
}

Employee_details_webapp/Employee_details_webapp/Controllers/CombinedController.cs
using System.Reflection.Metadata;
using DomainLayer.Models;
using Employee_details_webapp.Models;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using ServiceLayer.Services;

namespace Employee_details_webapp.Controllers
{
    public class CombinedController : Controller
    { 

        private readonly IPositionService _positionService;
        private readonly IPeopleService _peopleService;
        private readonly IEmployeeService _employeeService;
        private readonly IEmployeeJobHistoryService _employeeJobHistory;

        public CombinedController(IPositionService positionService, IPeopleService peopleService,IEmployeeService employeeService, IEmployeeJobHistoryService employeeJobHistory)
        {
            _positionService = positionService;
            _peopleService = peopleService;
            _employeeService = employeeService;
            _employeeJobHistory = employeeJobHistory;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AllEmployeesList()
        {
            var employees = _employeeService.GetAllEmployees().ToList();
            var people = _peopleService.GetAllPeople().ToList();
            var positions = _positionService.GetAllPositions().ToList();

            List<CombinedViewModel> combinedViewModelList = new List<CombinedViewModel>();

            employees.ForEach(employee =>
            {
                People people = _peopleService.GetPeople(employee.Personid);
                Positions position = _positionService.GetPosition(employee.Positionid);

                CombinedViewModel combinedViewModel = new()
                {
                    
                    FirstName = people.FirstName,
                    MiddleName = people.MiddleName,
                    LastName = people.LastName,
                    Address = people.Address,
                    Email = people.Email,
                    Employeeid = employee.Employeeid,
                    EmployeeCode = employee.EmployeeCode,
                    Salary = employee.Salary,
                    StartDate = DateOnly.FromDateTime(employee.StartDate),
                    EndDate = DateOnly.FromDateTime(employee.EndDate),
                    ISDisabled = employee.ISDisabled,
                    PositionName = position.PositionName
                };
                combinedViewModelList.Add(combinedViewModel);
            });

            return View(combinedViewModelList);
        }

        [HttpGet]
        public IActionResult AddEmployee()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEmployee(AddViewModel addRequest)
        {
            var people = new People()
            {
                Personid = Guid.NewGuid(),
                FirstName = addRequest.FirstName,
                MiddleName = addRequest.MiddleName,
                LastName = addRequest.LastName,
                Address = addRequest.Address,
                Email = addRequest.Email

            };

            _peopleService.InsertPeople(people);
            //return RedirectToAction("AllEmployeesList");

            var position = new Positions()
            {
                Positionid = Guid.NewGuid(),
                PositionName = "developer"
            };

            _positionService.InsertPosition(position);

            var employees = new Employees()
            {
                Employeeid = Guid.NewGuid(),
                EmployeeCode = addRequest.EmployeeCode,
                StartDate = addRequest.StartDate,
                EndDate = addRequest.EndDate,
                Salary = addRequest.Salary,
                Personid = people.Personid,
                Positionid = position.Positionid,
            };
            _employeeService.InsertEmployee(employees);
            return RedirectToAction("AllEmployeesList");

            //return View();
        }
    }
}

Employee_details_webapp/Employee_details_webapp/Controllers/HomeController.cs
using System.Diagnostics;
using Employee_details_webapp.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_details_webapp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Employee_details_webapp/Employee_details_webapp/Controllers/PositionController.cs
using DomainLayer.Models;
using Employee_details_webapp.Models;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using ServiceLayer.Services;

namespace Employee_details_webapp.Controllers
{
    public class PositionController : Controller
    {

        private readonly IPositionService _positionService;

        public PositionController(IPositionService positionService)
        {
            _positionService = positionService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AllPositionList()
        {
            var data = _positionService.GetAllPositions().ToList();
            return View(data);
        }

        [HttpGet]
        public IActionResult AddPosition()
        {
            ViewBag.data = _positionService.GetAllPositions().ToList();
            return View();
        }

        [HttpPost]
        public IActionResult AddPosition(PositionViewModel positionviewmodel)
        {

            if (positionviewmodel != null)
            {

                Positions positions = new()
                {
                    Positionid = Guid.NewGuid(),
                    PositionName = positionviewmodel.PositionName
                };

                _positionService.InsertPosition(positions);
                return RedirectToAction("AddPosition");
            }
            return RedirectToAction("AddPosition");
        }
    }
}

Employee_details_webapp/Employee_details_webapp/Views/Combined/AddEmployee.cshtml
@model Employee_details_webapp.Models.AddViewModel
<h1>Add employee:</h1>

<form method="post" action="AddEmployee" id="employeeform">
    <div class="mb-3">
        <label asp-for="FirstName" class="form-label">FirstName</label>
        <input type="text" class="form-control" asp-for="FirstName">
    </div>
    <div class="mb-3">
            <label asp-for="MiddleName" class="form-label">MiddleName</label>
            <input type="text" class="form-control" asp-for="MiddleName">
    </div>
    <div class="mb-3">
        <label asp-for="LastName" class="form-label">LastName</label>
            <input type="text" class="form-control" asp-for="LastName">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>
        <div class="mb-3">
        <label asp-for="Address" class="form-label">Address</label>
        <input type="text" class="form-control" asp-for="Address">
    </div>
    <div class="mb-3">
        <label asp-for="Salary" class="form-label">salary</label>
        <input type="text" class="form-control" asp-for="Salary">
        
    </div>
    <div class="mb-3">
        <label asp-for="EmployeeCode" class="form-label">code</label>
        <input type="number" class="form-control" asp-for="EmployeeCode">
      
    </div>
    <div class="mb-3">
        <label asp-for="StartDate" class="form-label">start Date</label>
        <input type="date" class="form-control"  asp-for="StartDate">
       
    </div>
    <div class="mb-3">
        <label asp-for="EndDate" class="form-label">end Date</label>
        <input type="date" class="form-control"  asp-for="EndDate">
        
    </div>
    
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

Employee_details_webapp/Employee_details_webapp/Views/Combined/AllEmployeesList.cshtml
@model List<Employee_details_webapp.Models.CombinedViewModel>
@{
}
<h1> Employees</h1>

<table class="table">
	<thead>
		<tr>
			<th>Code</th>
			<th>Full Name</th>
			<th>Email</th>
			<th>Address</th>
			<th>Salary</th>
			<th>Position</th>
			<th>Start Date</th>
			<th>End Date</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach(var Employees in Model)
		{
				<tr>
				<td>@Employees.EmployeeCode</td>
				<td>@Employees.FirstName @Employees.MiddleName @Employees.LastName</td>
				<td>@Employees.Email</td>
				<td>@Employees.Address</td>
				<td>@Employees.Salary</td>
				<td>@Employees.PositionName</td>
				<td>@Employees.StartDate</td>
				<td>@Employees.EndDate</td>
				</tr>
		}
	</tbody>
</table>

Employee_details_webapp/Employee_details_webapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Employee_details_webapp/Employee_details_webapp/Views/Position/AddPosition.cshtml
@model DomainLayer.Models.Positions

<h2> Positions</h2>

<table class="table">
	<thead>
		<tr>
			<th>Position Code</th>
			<th>Position Name</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var Positions in ViewBag.data)
		{
			<tr>
				<td>@Positions.Positionid</td>
				<td>@Positions.PositionName</td>
				<td><a href="">Delete</a></td>
			</tr>
		}
	</tbody>
</table>

<h2>Add Position:</h2>

<form method="post" action="AddPosition" id="employeeform">
    <div class="mb-3">
        <label asp-for="PositionName" class="form-label">Position Name</label>
        <input type="text" class="form-control" asp-for="PositionName">
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Add</button>
    </div>
</form>

Employee_details_webapp/Employee_details_webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee_details_webapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employee_details_webapp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee_details_webapp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Combined" asp-action="AddEmployee">Add Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Combined" asp-action="AllEmployeesList">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Position" asp-action="AddPosition">Positions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Employee_details_webapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>